name: EternalCentury
main: com.ec.ECCore
version: 0.0.1
api-version: 1.16
load: STARTUP
loadbefore:
  - mcMMO
  - Residence
  - MangoQuest
  - PlayerParticles
depend:
  - Reactant
  - NBTAPI
  - UniversalGUI
  - PlaceholderAPI
  - Citizens
  - Resquare
  - Vault
  - SkinsRestorer