package com.ec.model

// ref: https://forum.maestrea.com/threads/minecraft-symbols-emoticons-and-characters.11264/
enum class Emoji(val text: String) {
    AXE("\uD83E\uDE93"),
    PICKAXE("⛏"),
    FISHING_ROD("\uD83C\uDFA3"),
    SWORD("\uD83D\uDDE1"),
    TRIDENT("\uD83D\uDD31"),
    BOW("\uD83C\uDFF9"),
    POTION("\uD83E\uDDEA"),
    SPLASH_POTION("⚗"),
    FIRE("\uD83D\uDD25"),
    DUAL_SWORD("⚔"),
    TOOLS("⚒"),
    SHIELD("\uD83D\uDEE1"),
    SKULL("☠"),
    YIN_YANG("☯"),
    SPADE("♠"),
    OUTLINED_SPADE("♤"),
    CLUB("♣"),
    OUTLINED_CLUB("♧"),
    HEART("♥"),
    OUTLINED_HEART("♡"),
    DIAMOND("♦"),
    OUTLINED_DIAMOND("♢"),
    STAR("✯"),
    METEOR("☄"),
    MOON("☽"),
    SUN("☀"),
    CLOUD("☁"),
    UMBRELLA("☂"),
    SNOWMAN("☃"),
    SMILE_FACE("☺"),
    SAD_FACE("☹"),
    MAIL("✉"),
    RADIOACTIVE("☢"),
    INFECTION("☣"),
    SCISSOR("✂"),
    FEMALE("♂"),
    MALE("♀"),
    FEMALE_TEXT("㊛"),
    MALE_TEXT("㊚"),
    CROSS("✖"),
    ARROW("➹")
}